import React, { Suspense } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import SyncLoader from "react-spinners/SyncLoader";

const PaintingGallery = React.lazy(() =>
  import("@/components/gallery/PaintingGallery")
);

const inter = Inter({ subsets: ["latin"] });

export default function Home({ gallery, arts }) {
  return (
    <>
      <Head>
        <title>Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className="art-gallery mb-4">
          <Suspense fallback={<SyncLoader color="#36d7b7" />}>
            <PaintingGallery data={gallery} />
          </Suspense>
        </section>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const { art } = await import("../data/PaintingData.json");
  const { art_spe } = await import("../data/PaintingData.json");
  return {
    props: {
      gallery: art,
      arts: art_spe,
    },
  };
}
